# -------------------------------------------------------------
# Stonecutter node: 26.2-fabric
# Properties specific to the Fabric loader on Minecraft 26.2.
# -------------------------------------------------------------

# Use plain Fabric Loom for the 26.x line.
modstitch.platform=fabric-loom

# Minecraft version for this node
deps.minecraft=26.2

# Fabric Loader
deps.fabric_loader=0.19.3

# Fabric API
deps.fabric_api=0.152.1+26.2

# ModMenu
deps.modmenu=20.0.0-beta.2

# Cloth Config
deps.cloth_config=26.2.155
