# -------------------------------------------------------------
# Stonecutter node: 26.2-neoforge
# Properties specific to the NeoForge loader on Minecraft 26.2.
# -------------------------------------------------------------

# Activate NeoForge ModDevGradle for this node
modstitch.platform=moddevgradle

# Minecraft version for this node
deps.minecraft=26.2

# NeoForge
deps.neoforge=26.2.0.7-beta

# Cloth Config
deps.cloth_config=26.2.155
