# -------------------------------------------------------------
# Stonecutter node: 26.1.2-fabric
# Properties specific to the Fabric loader on Minecraft 26.1.2.
# -------------------------------------------------------------

# Use plain Fabric Loom for the 26.x line.
modstitch.platform=fabric-loom

# Minecraft version for this node
deps.minecraft=26.1.2

# Fabric Loader
deps.fabric_loader=0.19.2

# Fabric API
deps.fabric_api=0.148.0+26.1.2

# ModMenu
deps.modmenu=18.0.0-beta.1

# Cloth Config
deps.cloth_config=26.1.154
