modLoader="javafml"
loaderVersion="${neoforge_loader_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''
authors="${mod_author}"

[[mixins]]
config="minersadvantage.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="yet_another_config_lib_v3"
type="required"
versionRange="${yacl_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="cloth_config"
type="optional"
side="CLIENT"
